name: EAS Update
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '**.md'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g eas-cli@20.4.0
      - run: npm install
      - run: echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
      - run: eas update --branch preview --platform all --message "Auto update" --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
